services:
  postgres:
    image: postgres:15
    container_name: ecomstore_db
    environment:
      POSTGRES_USER: quan
      POSTGRES_PASSWORD: quan
      POSTGRES_DB: ecomstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecomstore_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  # backend:
  #     image: node:20-alpine
  #     container_name: medusa_backend
  #     working_dir: /app/medusa
  #     command: sh -c "npm install && npm run build && npm run dev"
  #     ports:
  #       - "9000:9000"
  #     # volumes:
  #     #   - ./my-medusa-store:/app
  #     #   - medusa_node_modules:/app/node_modules
  #     # environment:
  #     #   DATABASE_URL: postgres://quan:quan@postgres:5432/ecomstore
  #     #   NODE_ENV: development
  #     depends_on:
  #       - postgres
 
  # storefront:
  #   image: node:20-alpine
  #   container_name: medusa_storefront
  #   working_dir: /app/storefront
  #   command: sh -c "npm install && npm run dev"
  #   ports:
  #     - "8000:8000"
  #   # volumes:
  #   #   - ./my-medusa-store-storefront:/app
  #   #   - storefront_node_modules:/app/node_modules
  #   # environment:
  #   #   NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://backend:9000
  #   #   NODE_ENV: development
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
  pgadmin_data: