DEBUG = True

HISTORY_LENGTH = 20

DEVICE = "cpu" # "cpu" or "cuda:0"

if DEVICE == "cuda:0":
    RETRIEVED_DOCUMENTS_QUANTITY = 15
    RERANKED_DOCUMENTS_QUANTITY = 8
else:
    RETRIEVED_DOCUMENTS_QUANTITY = 8
    RERANKED_DOCUMENTS_QUANTITY = 8